version: '3'
services:
  node1-be:
    build: node-backend
    environment:
     - SERVER_NAME=A
  node2-be:
    build: node-backend
    environment:
     - SERVER_NAME=B
  node-web:
    build: node-web
  nginx-fe:
    build: nginx-frontend
    ports:
    - "80:80"